
# this file works as a combination of Dockerfile arguments and Docker tags
# x: ["y", "z"] means the variable is x, and it is reflected in Docker tags y and z.
# tags should decrease in specificity along the list
# a blank tag means it is implicit when omitted
# this is used to automatically generate the Dockerfiles, metadata and readme.

# When updating this ALSO UPDATE .github/workflows/docker-build.yml !!
python_versions:
  #"3.13.0rc2":  ["3.13.0rc2", "3.13.0", "3.13"]
  "3.12.6":     ["3.12.6", "3.12", ""]
  "3.11.10":    ["3.11.10", "3.11"]
  "3.10.15":    ["3.10.15", "3.10"]
  "3.9.20":     ["3.9.20", "3.9"]
  "3.8.20":     ["3.8.20", "3.8"]

distros:
  bookworm: ["bookworm", ""]
  slim-bookworm: ["slim-bookworm", "slim"]
  bullseye: ["bullseye", ""]
  slim-bullseye: ["slim-bullseye"]
  alpine: ["alpine"]

checkouts:
  master: ["master", "dev", "2.5a", "2.5"]
  "": ["pypi", "2.4", "2", ""]

# these don't follow the above syntax as they're just pulled by the templates
minor_deps:
  asyncpg: asyncpg
  click: click
  coverage: coverage
  flake8: flake8
  lxml: lxml
  matplotlib: matplotlib
  Pillow: Pillow
  psutil: psutil
  pycryptodome: pycryptodome
  pylint: pylint
  pytest-cov: pytest-cov
  PyYAML: PyYAML
  ruamel.yaml: "ruamel.yaml"
  toml: toml
  twine: twine

major_deps:
  aiomysql: aiomysql
  beautifulsoup4: beautifulsoup4
  cairosvg: cairosvg
  colorlog: colorlog
  colorthief: colorthief
  fuzzywuzzy: fuzzywuzzy[speedup]
  humanize: humanize
  lru-dict: lru-dict
  objgraph: objgraph
  parsedatetime: parsedatetime
  python-dateutil: python-dateutil
  redis: redis
  sqlalchemy: sqlalchemy
  tabulate: tabulate
  tox: tox
  wand: wand

stage_types:
  0: ['minimal']
  1: ['full', '']
  2: ['extras']
