#!/bin/bash
set -euo pipefail

echo "Building stage 1 (full)"

if docker build --no-cache -f trixie.Dockerfile --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=$1 --tag discord.py:build1-$1-trixie --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-$1-trixie .; then echo -e "BUILD build1-$1-trixie" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-$1-trixie" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f slim-trixie.Dockerfile --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=$1 --tag discord.py:build1-$1-slim-trixie --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-$1-slim-trixie .; then echo -e "BUILD build1-$1-slim-trixie" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-$1-slim-trixie" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f bookworm.Dockerfile --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=$1 --tag discord.py:build1-$1-bookworm --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-$1-bookworm .; then echo -e "BUILD build1-$1-bookworm" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-$1-bookworm" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f slim-bookworm.Dockerfile --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=$1 --tag discord.py:build1-$1-slim-bookworm --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-$1-slim-bookworm .; then echo -e "BUILD build1-$1-slim-bookworm" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-$1-slim-bookworm" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f alpine.Dockerfile --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=$1 --tag discord.py:build1-$1-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-$1-alpine .; then echo -e "BUILD build1-$1-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-$1-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
